/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruben
 */
public class Configuracion extends javax.swing.JDialog {

    /**
     * Creates new form Configuracion
     */
    public Configuracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantIterLabel = new javax.swing.JLabel();
        cantIterTextField = new javax.swing.JTextField();
        tamPobLabel = new javax.swing.JLabel();
        tamPobTextField = new javax.swing.JTextField();
        panelOperadores = new javax.swing.JPanel();
        panelSeleccion = new javax.swing.JPanel();
        panelChecksSelec = new javax.swing.JPanel();
        elitistaCheck = new javax.swing.JCheckBox();
        ruletaCheck = new javax.swing.JCheckBox();
        rankingCheck = new javax.swing.JCheckBox();
        controlCECheck = new javax.swing.JCheckBox();
        porTorneoCheck = new javax.swing.JCheckBox();
        porTorneoTextField = new javax.swing.JTextField();
        porcentSelecLabel = new javax.swing.JLabel();
        porcentSelecTextField = new javax.swing.JTextField();
        editarSeleccionButton = new javax.swing.JButton();
        panelCruza = new javax.swing.JPanel();
        panelChecksCruza = new javax.swing.JPanel();
        simpleCheck = new javax.swing.JCheckBox();
        multipuntoCheck = new javax.swing.JCheckBox();
        binomialCheck = new javax.swing.JCheckBox();
        porcentCruzaLabel = new javax.swing.JLabel();
        porcentCruzaTextField = new javax.swing.JTextField();
        editarCruzaButton = new javax.swing.JButton();
        editarCantIterButton = new javax.swing.JButton();
        editarTamPobButton = new javax.swing.JButton();
        aceptarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setIconImage(null);
        setResizable(false);

        cantIterLabel.setText("Cantidade de Iteraciones:");

        cantIterTextField.setEnabled(false);

        tamPobLabel.setText("Tamaño de la Poblacion:");

        tamPobTextField.setEnabled(false);

        panelOperadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Operadores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        panelSeleccion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Seleccion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        panelChecksSelec.setLayout(new java.awt.GridLayout(3, 0));

        elitistaCheck.setText("Elitista");
        panelChecksSelec.add(elitistaCheck);

        ruletaCheck.setText("Ruleta");
        panelChecksSelec.add(ruletaCheck);

        rankingCheck.setText("Ranking");
        panelChecksSelec.add(rankingCheck);

        controlCECheck.setText("Control de copias esperada");
        panelChecksSelec.add(controlCECheck);

        porTorneoCheck.setText("Por torneo");
        porTorneoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porTorneoCheckActionPerformed(evt);
            }
        });
        panelChecksSelec.add(porTorneoCheck);

        porTorneoTextField.setEnabled(false);
        porTorneoTextField.setMaximumSize(new java.awt.Dimension(6, 20));
        panelChecksSelec.add(porTorneoTextField);

        porcentSelecLabel.setText("Porcentaje de Selección:");

        porcentSelecTextField.setEnabled(false);

        editarSeleccionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/lapicito edit 16.png"))); // NOI18N
        editarSeleccionButton.setText("Editar");
        editarSeleccionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarSeleccionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeleccionLayout = new javax.swing.GroupLayout(panelSeleccion);
        panelSeleccion.setLayout(panelSeleccionLayout);
        panelSeleccionLayout.setHorizontalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChecksSelec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelSeleccionLayout.createSequentialGroup()
                        .addComponent(porcentSelecLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porcentSelecTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarSeleccionButton)))
                .addContainerGap())
        );
        panelSeleccionLayout.setVerticalGroup(
            panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeleccionLayout.createSequentialGroup()
                .addComponent(panelChecksSelec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentSelecLabel)
                    .addComponent(porcentSelecTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarSeleccionButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCruza.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Cruza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));

        panelChecksCruza.setLayout(new java.awt.GridLayout(1, 0));

        simpleCheck.setText("Simple");
        panelChecksCruza.add(simpleCheck);

        multipuntoCheck.setText("Multipunto");
        panelChecksCruza.add(multipuntoCheck);

        binomialCheck.setText("Binomial");
        panelChecksCruza.add(binomialCheck);

        porcentCruzaLabel.setText("Porcentaje de Cruza:");

        porcentCruzaTextField.setEnabled(false);

        editarCruzaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/lapicito edit 16.png"))); // NOI18N
        editarCruzaButton.setText("Editar");
        editarCruzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCruzaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCruzaLayout = new javax.swing.GroupLayout(panelCruza);
        panelCruza.setLayout(panelCruzaLayout);
        panelCruzaLayout.setHorizontalGroup(
            panelCruzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChecksCruza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCruzaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(porcentCruzaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porcentCruzaTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarCruzaButton)
                .addContainerGap())
        );
        panelCruzaLayout.setVerticalGroup(
            panelCruzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCruzaLayout.createSequentialGroup()
                .addComponent(panelChecksCruza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCruzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(porcentCruzaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCruzaButton)
                    .addComponent(porcentCruzaLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelOperadoresLayout = new javax.swing.GroupLayout(panelOperadores);
        panelOperadores.setLayout(panelOperadoresLayout);
        panelOperadoresLayout.setHorizontalGroup(
            panelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCruza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelOperadoresLayout.setVerticalGroup(
            panelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperadoresLayout.createSequentialGroup()
                .addComponent(panelSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCruza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        editarCantIterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/lapicito edit 16.png"))); // NOI18N
        editarCantIterButton.setText("Editar");
        editarCantIterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCantIterButtonActionPerformed(evt);
            }
        });

        editarTamPobButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/lapicito edit 16.png"))); // NOI18N
        editarTamPobButton.setText("Editar");
        editarTamPobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTamPobButtonActionPerformed(evt);
            }
        });

        aceptarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/icon_confirm.png"))); // NOI18N
        aceptarButton.setText("Aceptar");
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamPobLabel)
                            .addComponent(cantIterLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tamPobTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(cantIterTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarCantIterButton)
                            .addComponent(editarTamPobButton)))
                    .addComponent(panelOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cantIterLabel)
                    .addComponent(cantIterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCantIterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tamPobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tamPobLabel)
                    .addComponent(editarTamPobButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptarButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void porTorneoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porTorneoCheckActionPerformed
        porTorneoTextField.setEnabled(porTorneoCheck.isSelected());
    }//GEN-LAST:event_porTorneoCheckActionPerformed

    private void editarCantIterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCantIterButtonActionPerformed
        cantIterTextField.setEnabled(!cantIterTextField.isEnabled());
        String texto = "";
        if (cantIterTextField.isEnabled()) {
            texto = "Listo";
        } else {
            texto = "Editar";
        }
        editarCantIterButton.setText(texto);
    }//GEN-LAST:event_editarCantIterButtonActionPerformed

    private void editarTamPobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTamPobButtonActionPerformed
        tamPobTextField.setEnabled(!tamPobTextField.isEnabled());
        String texto = "";
        if (tamPobTextField.isEnabled()) {
            texto = "Listo";
        } else {
            texto = "Editar";
        }
        editarTamPobButton.setText(texto);
    }//GEN-LAST:event_editarTamPobButtonActionPerformed

    private void editarSeleccionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarSeleccionButtonActionPerformed
        porcentSelecTextField.setEnabled(!porcentSelecTextField.isEnabled());
        String texto = "";
        if (porcentSelecTextField.isEnabled()) {
            texto = "Listo";
        } else {
            texto = "Editar";
        }
        editarSeleccionButton.setText(texto);
    }//GEN-LAST:event_editarSeleccionButtonActionPerformed

    private void editarCruzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCruzaButtonActionPerformed
        porcentCruzaTextField.setEnabled(!porcentCruzaTextField.isEnabled());
        String texto = "";
        if (porcentCruzaTextField.isEnabled()) {
            texto = "Listo";
        } else {
            texto = "Editar";
        }
        editarCruzaButton.setText(texto);
    }//GEN-LAST:event_editarCruzaButtonActionPerformed

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        if (cantIterTextField.isEnabled()
                || tamPobTextField.isEnabled()
                || porcentSelecTextField.isEnabled()
                || porcentCruzaTextField.isEnabled()) {
            JOptionPane.showMessageDialog(this, "Confirme 'listo' en las opciones de la configuracion", "Confirmacion de cambios", JOptionPane.WARNING_MESSAGE);
        } else {
        dispose();
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configuracion dialog = new Configuracion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JCheckBox binomialCheck;
    private javax.swing.JLabel cantIterLabel;
    private javax.swing.JTextField cantIterTextField;
    private javax.swing.JCheckBox controlCECheck;
    private javax.swing.JButton editarCantIterButton;
    private javax.swing.JButton editarCruzaButton;
    private javax.swing.JButton editarSeleccionButton;
    private javax.swing.JButton editarTamPobButton;
    private javax.swing.JCheckBox elitistaCheck;
    private javax.swing.JCheckBox multipuntoCheck;
    private javax.swing.JPanel panelChecksCruza;
    private javax.swing.JPanel panelChecksSelec;
    private javax.swing.JPanel panelCruza;
    private javax.swing.JPanel panelOperadores;
    private javax.swing.JPanel panelSeleccion;
    private javax.swing.JCheckBox porTorneoCheck;
    private javax.swing.JTextField porTorneoTextField;
    private javax.swing.JLabel porcentCruzaLabel;
    private javax.swing.JTextField porcentCruzaTextField;
    private javax.swing.JLabel porcentSelecLabel;
    private javax.swing.JTextField porcentSelecTextField;
    private javax.swing.JCheckBox rankingCheck;
    private javax.swing.JCheckBox ruletaCheck;
    private javax.swing.JCheckBox simpleCheck;
    private javax.swing.JLabel tamPobLabel;
    private javax.swing.JTextField tamPobTextField;
    // End of variables declaration//GEN-END:variables
}
