/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import dominio.Individuo;
import javax.swing.JLabel;

/**
 *
 * @author Ruben
 */
public class Resultado extends javax.swing.JDialog {

    /**
     * Creates new form Resultado
     */
    private Individuo individuo1;
    private Individuo individuo2;
    private Individuo individuo3;
    private int[] materialesIngresados;

    public Resultado(java.awt.Frame parent, boolean modal, Individuo[] individuos, int[] mIngresados) {
        super(parent, modal);
        initComponents();
        setTitle("Resultados");
        setLocationRelativeTo(null);
        individuo1 = individuos[0];
        individuo2 = individuos[1];
        individuo3 = individuos[2];
        materialesIngresados = mIngresados;
        agregarResultados();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combinacionesPanel = new javax.swing.JPanel();
        posicionLabel = new javax.swing.JLabel();
        indivLabel = new javax.swing.JLabel();
        utilidadLabel = new javax.swing.JLabel();
        recetaLabel = new javax.swing.JLabel();
        pos1Label = new javax.swing.JLabel();
        ind1Label = new javax.swing.JLabel();
        u1Label = new javax.swing.JLabel();
        receta1Label = new javax.swing.JButton();
        pos2Label = new javax.swing.JLabel();
        ind2Label = new javax.swing.JLabel();
        u2Label = new javax.swing.JLabel();
        receta2Label = new javax.swing.JButton();
        pos3Label = new javax.swing.JLabel();
        ind3Label = new javax.swing.JLabel();
        u3Label = new javax.swing.JLabel();
        receta3Label = new javax.swing.JButton();
        aceptarLabel = new javax.swing.JButton();

        setResizable(false);

        combinacionesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Tres mejores combinaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(102, 102, 102)));
        combinacionesPanel.setLayout(new java.awt.GridLayout(4, 4, 0, 4));

        posicionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        posicionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicionLabel.setText("Posicion");
        combinacionesPanel.add(posicionLabel);

        indivLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        indivLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        indivLabel.setText("Individuo");
        combinacionesPanel.add(indivLabel);

        utilidadLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        utilidadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        utilidadLabel.setText("Utilidad [$]");
        combinacionesPanel.add(utilidadLabel);

        recetaLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        recetaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recetaLabel.setText("Receta");
        combinacionesPanel.add(recetaLabel);

        pos1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pos1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos1Label.setText("1");
        combinacionesPanel.add(pos1Label);

        ind1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ind1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind1Label.setText("(0,0,0,0)");
        combinacionesPanel.add(ind1Label);

        u1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u1Label.setText("0.0");
        combinacionesPanel.add(u1Label);

        receta1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/quimica.png"))); // NOI18N
        receta1Label.setText("Ver");
        receta1Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receta1LabelActionPerformed(evt);
            }
        });
        combinacionesPanel.add(receta1Label);

        pos2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pos2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos2Label.setText("2");
        combinacionesPanel.add(pos2Label);

        ind2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ind2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind2Label.setText("(0,0,0,0)");
        combinacionesPanel.add(ind2Label);

        u2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u2Label.setText("0.0");
        combinacionesPanel.add(u2Label);

        receta2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/quimica.png"))); // NOI18N
        receta2Label.setText("Ver");
        receta2Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receta2LabelActionPerformed(evt);
            }
        });
        combinacionesPanel.add(receta2Label);

        pos3Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pos3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos3Label.setText("3");
        combinacionesPanel.add(pos3Label);

        ind3Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ind3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ind3Label.setText("(0,0,0,0)");
        combinacionesPanel.add(ind3Label);

        u3Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u3Label.setText("0.0");
        combinacionesPanel.add(u3Label);

        receta3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/quimica.png"))); // NOI18N
        receta3Label.setText("Ver");
        receta3Label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receta3LabelActionPerformed(evt);
            }
        });
        combinacionesPanel.add(receta3Label);

        aceptarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/icons/icon_confirm.png"))); // NOI18N
        aceptarLabel.setText("Aceptar");
        aceptarLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(combinacionesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(aceptarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(combinacionesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aceptarLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void receta1LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receta1LabelActionPerformed
        Recetas r = new Recetas(null, true,"Receta Primer Individuo");
        int[][] receta = individuo1.calcularReceta(materialesIngresados);
        r.cargarReceta(receta);
        r.cargarDesperdicio(individuo1.calcularDesperdicios(receta, materialesIngresados));
        r.cargarUtilizacion(individuo1.calcularUso(receta));
        r.pack();
        r.setVisible(true);
    }//GEN-LAST:event_receta1LabelActionPerformed

    private void aceptarLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarLabelActionPerformed
        this.dispose();
    }//GEN-LAST:event_aceptarLabelActionPerformed

    private void receta2LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receta2LabelActionPerformed
        Recetas r = new Recetas(null, true,"Receta Segundo Individuo");
        int[][] receta = individuo2.calcularReceta(materialesIngresados);
        r.cargarReceta(receta);
        r.cargarDesperdicio(individuo2.calcularDesperdicios(receta, materialesIngresados));
        r.cargarUtilizacion(individuo2.calcularUso(receta));
        r.pack();
        r.setVisible(true);
    }//GEN-LAST:event_receta2LabelActionPerformed

    private void receta3LabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receta3LabelActionPerformed
        Recetas r = new Recetas(null, true,"Receta Tercer Individuo");
        int[][] receta = individuo2.calcularReceta(materialesIngresados);
        r.cargarReceta(receta);
        r.cargarDesperdicio(individuo2.calcularDesperdicios(receta, materialesIngresados));
        r.cargarUtilizacion(individuo2.calcularUso(receta));
        r.pack();
        r.setVisible(true);
    }//GEN-LAST:event_receta3LabelActionPerformed

    private void agregarResultados() {
        getInd1Label().setText(individuo1.mostrarProductos());
        getInd2Label().setText(individuo2.mostrarProductos());
        getInd3Label().setText(individuo3.mostrarProductos());
        getU1Label().setText(String.valueOf(individuo1.getUtilidad()));
        getU2Label().setText(String.valueOf(individuo2.getUtilidad()));
        getU3Label().setText(String.valueOf(individuo3.getUtilidad()));
    }

    public JLabel getInd1Label() {
        return ind1Label;
    }

    public JLabel getInd2Label() {
        return ind2Label;
    }

    public JLabel getInd3Label() {
        return ind3Label;
    }

    public JLabel getU1Label() {
        return u1Label;
    }

    public JLabel getU2Label() {
        return u2Label;
    }

    public JLabel getU3Label() {
        return u3Label;
    }

    public Individuo getIndividuo1() {
        return individuo1;
    }

    public Individuo getIndividuo2() {
        return individuo2;
    }

    public Individuo getIndividuo3() {
        return individuo3;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarLabel;
    private javax.swing.JPanel combinacionesPanel;
    private javax.swing.JLabel ind1Label;
    private javax.swing.JLabel ind2Label;
    private javax.swing.JLabel ind3Label;
    private javax.swing.JLabel indivLabel;
    private javax.swing.JLabel pos1Label;
    private javax.swing.JLabel pos2Label;
    private javax.swing.JLabel pos3Label;
    private javax.swing.JLabel posicionLabel;
    private javax.swing.JButton receta1Label;
    private javax.swing.JButton receta2Label;
    private javax.swing.JButton receta3Label;
    private javax.swing.JLabel recetaLabel;
    private javax.swing.JLabel u1Label;
    private javax.swing.JLabel u2Label;
    private javax.swing.JLabel u3Label;
    private javax.swing.JLabel utilidadLabel;
    // End of variables declaration//GEN-END:variables
}
